name: copy_with_macro
description: "A @CopyWith() macros, built on top of Metaprogramming feature of Dart to copy classes with nullable values"
version: 0.0.1
homepage:

environment:
  sdk: '>=3.5.0-191.0.dev <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  macros: ^0.1.2-main.3
  data_class: ^0.0.2
  json: ^0.20.2
# For experiments
#  macros: ^0.1.2-main.3
#  data_class: ^0.0.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  nanc_lints: ^1.0.0

flutter: